---
title: "CodeBook"
author: "Kyle Becker"
date: "February 20, 2017"
output: html_document
---

## Data Summary

The following raw data set was obtained from the UCI Machine learning Repository. This data set was collected using 30 volunteers. Each volunteer was between the ages of 19 and 48 years old and was given a smartphone (Samsung Galaxy S II) which was attached to their waist. Each volunteer wearing the smartphone was asked to complete six different forms of motion specifically walking, walking upsatairs, walking downstairs, sitting, standing, laying. Using the smartphones embedded accelerometer and gyroscope, the researchers captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. 

## Variable Explanation
Each subject had the following informationt tracked:

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration. 
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.


##Variable list and type of starting Data Sets
The following data set was created by combining the X training set and the X Test set as well as the Y training set and Y Test set into one data frame. Once each of the 4 dataframes were combined into one. Then the columns were filtered to only include information that contained the word mean std(standard deviation) and the appropriate Acivity ID and Subject ID.

A summary of each variable type and name is included below:


```##  $ Activity.ID                    : int  1 1 1 1 1 1 1 1 1 1 ...
##  $ tBodyAcc.mean...X              : num  0.302 0.343 0.27 0.268 0.314 ...
##  $ tBodyAcc.mean...Y              : num  -0.02688 -0.00343 0.01091 -0.01273 -0.0087 ...
##  $ tBodyAcc.mean...Z              : num  -0.0958 -0.1015 -0.0749 -0.0937 -0.1246 ...
##  $ tBodyAcc.std...X               : num  -0.38 -0.201 -0.337 -0.384 -0.356 ...
##  $ tBodyAcc.std...Y               : num  -0.191 0.133 0.146 -0.204 -0.166 ...
##  $ tBodyAcc.std...Z               : num  0.341 -0.318 -0.446 0.148 0.407 ...
##  $ tGravityAcc.mean...X           : num  0.902 0.965 0.96 0.944 0.892 ...
##  $ tGravityAcc.mean...Y           : num  -0.137 -0.145 -0.214 -0.159 -0.147 ...
##  $ tGravityAcc.mean...Z           : num  -0.3428 0.0285 0.0505 -0.1425 -0.3414 ...
##  $ tGravityAcc.std...X            : num  -0.953 -0.984 -0.965 -0.981 -0.98 ...
##  $ tGravityAcc.std...Y            : num  -0.937 -0.953 -0.939 -0.973 -0.961 ...
##  $ tGravityAcc.std...Z            : num  -0.921 -0.99 -0.946 -0.966 -0.941 ...
##  $ tBodyAccJerk.mean...X          : num  0.1505 -0.1351 0.1262 -0.0358 -0.2256 ...
##  $ tBodyAccJerk.mean...Y          : num  -0.2391 -0.0637 0.2083 -0.0136 -0.0699 ...
##  $ tBodyAccJerk.mean...Z          : num  -0.1533 -0.2631 0.0773 0.2511 -0.0937 ...
##  $ tBodyAccJerk.std...X           : num  -0.472 -0.197 -0.159 -0.333 -0.453 ...
##  $ tBodyAccJerk.std...Y           : num  -0.1607 -0.0446 0.0551 -0.2088 -0.1215 ...
##  $ tBodyAccJerk.std...Z           : num  -0.06331 -0.44016 -0.47746 -0.05011 -0.00443 ...
##  $ tBodyGyro.mean...X             : num  0.2139 -0.0277 -0.0484 -0.0117 0.0334 ...
##  $ tBodyGyro.mean...Y             : num  -0.049 -0.1253 -0.1036 -0.0135 -0.0969 ...
##  $ tBodyGyro.mean...Z             : num  -0.24527 0.12289 0.08692 0.15683 -0.00968 ...
##  $ tBodyGyro.std...X              : num  -0.512 -0.448 -0.407 -0.501 -0.536 ...
##  $ tBodyGyro.std...Y              : num  -0.254 -0.394 -0.208 0.178 -0.239 ...
##  $ tBodyGyro.std...Z              : num  -0.404 -0.311 -0.288 -0.305 -0.362 ...
##  $ tBodyGyroJerk.mean...X         : num  -0.0634 0.0756 0.047 -0.1203 -0.203 ...
##  $ tBodyGyroJerk.mean...Y         : num  0.03158 -0.05686 -0.09651 -0.00423 -0.16378 ...
##  $ tBodyGyroJerk.mean...Z         : num  -0.0112 0.14377 0.00215 -0.18785 0.05743 ...
##  $ tBodyGyroJerk.std...X          : num  -0.228 -0.3 -0.148 -0.411 -0.235 ...
##  $ tBodyGyroJerk.std...Y          : num  -0.293 -0.454 -0.211 0.173 -0.279 ...
##  $ tBodyGyroJerk.std...Z          : num  -0.56075 -0.09672 -0.00331 -0.44637 -0.55917 ...
##  $ tBodyAccMag.mean..             : num  -0.0919 -0.0604 -0.1786 -0.1654 -0.0508 ...
##  $ tBodyAccMag.std..              : num  -0.219 -0.318 -0.331 -0.25 -0.193 ...
##  $ tGravityAccMag.mean..          : num  -0.0919 -0.0604 -0.1786 -0.1654 -0.0508 ...
##  $ tGravityAccMag.std..           : num  -0.219 -0.318 -0.331 -0.25 -0.193 ...
##  $ tBodyAccJerkMag.mean..         : num  -0.221 -0.177 -0.154 -0.165 -0.167 ...
##  $ tBodyAccJerkMag.std..          : num  -0.0879 -0.1895 -0.1146 -0.0714 -0.0674 ...
##  $ tBodyGyroMag.mean..            : num  -0.2319 -0.2911 -0.2321 -0.0934 -0.3111 ...
##  $ tBodyGyroMag.std..             : num  -0.359 -0.457 -0.169 0.095 -0.26 ...
##  $ tBodyGyroJerkMag.mean..        : num  -0.3526 -0.3462 -0.1846 -0.0862 -0.3425 ...
##  $ tBodyGyroJerkMag.std..         : num  -0.26 -0.432 -0.175 0.135 -0.255 ...
##  $ fBodyAcc.mean...X              : num  -0.426 -0.18 -0.229 -0.337 -0.377 ...
##  $ fBodyAcc.mean...Y              : num  -0.0972 0.0852 0.1118 -0.1718 -0.1915 ...
##  $ fBodyAcc.mean...Z              : num  0.1846 -0.3 -0.4013 0.0634 0.1929 ...
##  $ fBodyAcc.std...X               : num  -0.363 -0.21 -0.384 -0.403 -0.347 ...
##  $ fBodyAcc.std...Y               : num  -0.2983 0.0866 0.0919 -0.272 -0.2047 ...
##  $ fBodyAcc.std...Z               : num  0.319 -0.385 -0.52 0.104 0.41 ...
##  $ fBodyAcc.meanFreq...X          : num  -0.474 -0.348 -0.247 -0.324 -0.249 ...
##  $ fBodyAcc.meanFreq...Y          : num  0.2648 -0.1593 -0.0343 -0.0378 0.1274 ...
##  $ fBodyAcc.meanFreq...Z          : num  0.10475 0.2059 0.33348 0.11459 -0.00943 ...
##  $ fBodyAccJerk.mean...X          : num  -0.49 -0.2 -0.174 -0.353 -0.466 ...
##  $ fBodyAccJerk.mean...Y          : num  -0.189 -0.1399 -0.0781 -0.2802 -0.2017 ...
##  $ fBodyAccJerk.mean...Z          : num  0.0147 -0.39925 -0.41452 -0.06667 0.00383 ...
##  $ fBodyAccJerk.std...X           : num  -0.5 -0.269 -0.219 -0.372 -0.489 ...
##  $ fBodyAccJerk.std...Y           : num  -0.18651 -0.00372 0.12855 -0.18274 -0.09159 ...
##  $ fBodyAccJerk.std...Z           : num  -0.1381 -0.4783 -0.5398 -0.0346 -0.011 ...
##  $ fBodyAccJerk.meanFreq...X      : num  -0.325 -0.235 -0.283 -0.28 -0.426 ...
##  $ fBodyAccJerk.meanFreq...Y      : num  -0.263 -0.681 -0.593 -0.467 -0.171 ...
##  $ fBodyAccJerk.meanFreq...Z      : num  -0.25797 -0.25201 -0.00807 -0.45074 -0.32644 ...
##  $ fBodyGyro.mean...X             : num  -0.321 -0.311 -0.164 -0.368 -0.347 ...
##  $ fBodyGyro.mean...Y             : num  -0.201 -0.414 -0.185 0.127 -0.248 ...
##  $ fBodyGyro.mean...Z             : num  -0.4485 -0.157 -0.0698 -0.2908 -0.4522 ...
##  $ fBodyGyro.std...X              : num  -0.574 -0.491 -0.487 -0.544 -0.598 ...
##  $ fBodyGyro.std...Y              : num  -0.294 -0.387 -0.229 0.201 -0.239 ...
##  $ fBodyGyro.std...Z              : num  -0.445 -0.433 -0.441 -0.373 -0.393 ...
##  $ fBodyGyro.meanFreq...X         : num  0.044 0.0085 0.0896 -0.2157 0.134 ...
##  $ fBodyGyro.meanFreq...Y         : num  0.105 0.0201 0.0239 0.0392 0.0229 ...
##  $ fBodyGyro.meanFreq...Z         : num  -0.2098 0.2922 0.2877 -0.0887 -0.1607 ...
##  $ fBodyAccMag.mean..             : num  -0.224 -0.196 -0.213 -0.135 -0.168 ...
##  $ fBodyAccMag.std..              : num  -0.338 -0.505 -0.512 -0.44 -0.333 ...
##  $ fBodyAccMag.meanFreq..         : num  0.199 0.21 0.246 0.289 0.222 ...
##  $ fBodyBodyAccJerkMag.mean..     : num  -0.1081 -0.1625 -0.0958 -0.0753 -0.081 ...
##  $ fBodyBodyAccJerkMag.std..      : num  -0.0685 -0.2309 -0.139 -0.0728 -0.0562 ...
##  $ fBodyBodyAccJerkMag.meanFreq.. : num  0.03543 -0.00273 0.02406 0.05082 0.156 ...
##  $ fBodyBodyGyroMag.mean..        : num  -0.356 -0.414 -0.149 0.202 -0.255 ...
##  $ fBodyBodyGyroMag.std..         : num  -0.474 -0.589 -0.331 -0.192 -0.394 ...
##  $ fBodyBodyGyroMag.meanFreq..    : num  0.1883 0.3676 0.2685 0.4571 0.0931 ...
##  $ fBodyBodyGyroJerkMag.mean..    : num  -0.2935 -0.5085 -0.2354 0.0615 -0.2945 ...
##  $ fBodyBodyGyroJerkMag.std..     : num  -0.269 -0.382 -0.158 0.149 -0.256 ...
##  $ fBodyBodyGyroJerkMag.meanFreq..: num  -0.112 0.2 0.215 0.293 -0.151 ...
##  $ Subject.Label                  : int  7 5 6 23 7 7 11 6 10 11 ...
##  $ Activity.Label                 : Factor w/ 6 levels "LAYING","SITTING",..: 4 4 4 4 4 4 4 4 4 4 ..
```

Activity_ID: unique identifier (integer 1 to 6), determining the activity of each subject

Activity_Label: Descriptive name categorical variable of each Activity (Factor Variable  WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING)

Subject_ID : unique identifier (integer 1 to 30), identifying each subject (participant)

## Average of each Column by Subject and Activity

From this original data set a second data set was created with the average for each column by activity and subject. This was done using the aggregate function and then ordering the results by Subject ID and then Activity ID. A sample of the data is displayed below.

```{Second Data Set, echo=FALSE}
#Second Average Tidy Data Set
Tidy_DS <- aggregate(.~Subject.Label + Activity.ID, Activity_Names_DS, mean)
Tidy_DS_Ordered <- Tidy_DS[order(Tidy_DS$Subject.Label, Tidy_DS$Activity.ID),]
head(Tidy_DS_Ordered)
```

